<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <OutputType>Library</OutputType>
    <IsPackable>false</IsPackable>
    <Configurations>Debug;Release</Configurations>
    <NeutralLanguage>en-US</NeutralLanguage>
    <RollForward>Major</RollForward>

    <AssemblyName>MarkDigTest</AssemblyName>
    <AssemblyTitle>RJCP.MarkDigTest</AssemblyTitle>
    <Product>MarkDigTest</Product>
    <RootNamespace>RJCP.MarkDigTest</RootNamespace>

    <Authors>Jason Curl</Authors>
    <Copyright>(C) 2026, Jason Curl</Copyright>
    <Company></Company>
    <Description>PoC for inclusion block for Markdig.</Description>
    <Version>1.0.0</Version>

    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisMode>Default</AnalysisMode>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnableDefaultItems>false</EnableDefaultItems>
    <LangVersion Condition="$(TargetFramework.StartsWith('net4'))">10</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework'">
    <Reference Include="System" />
    <Reference Include="System.Core" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
    <PackageReference Include="NUnit" Version="4.5.1" />
    <PackageReference Include="NUnit.Analyzers" Version="4.12.0" />
    <PackageReference Include="NUnit.ConsoleRunner" Version="3.22.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
    <PackageReference Include="CSharpIsNullAnalyzer" Version="0.1.593" PrivateAssets="all" />
    <PackageReference Include="Markdig" Version="1.1.2" />
    <PackageReference Include="RJCP.CodeQuality" Version="0.6.3" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="ExtensionsHelper.cs" />
    <Compile Include="InclusionBlock.cs" />
    <Compile Include="InclusionBlockParser.cs" />
    <Compile Include="InclusionBlockRenderer.cs" />
    <Compile Include="InclusionExtension.cs" />
    <Compile Include="InclusionFiles.cs" />
    <Compile Include="MamlTopicRenderer.cs" />
    <Compile Include="MarkdownExtensionsTest.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" />
    <None Include="TestResources\Included.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="TestResources\Root.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="TestResources\subdir\common.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
